### ISSUE TITLE
capacity change clarification

### ISSUE THREAD

**Issue by Gellardo** [Gellardo/urbs.jl#3]
What happens if the installed capacity cap_init is bigger than the minimal capacity cap_min or the maximal capacity cap_max?

Options:
- allow downgrading of capacity and resulting negative costs
- allow downgrading of capacity but with positive costs
- set cap_min = cap_init

**Comment by ojdo** [comment]
I would opt for the following behaviour:
- `cap_init > cap_min`: no problem; a very cautious reaction could be to issue a warning (but only triggered by some kind of verbose setting)
- `cap_init > cap_max`: no problem: usually, the solver would directly return "infeasible problem", and its log file could reveal the offending constraint. Possibly better is  throw error already during model generation. But this would be much more work in the long run, because there are in principle at least over a dozen of such simple cases; and all will be ultimately "checked" automatically by the solver. However, to have such a pre-check with hand-crafted tests and error messages could save a lot of modellers a lot of time...

**Comment by Gellardo** [comment]
Well, I just noticed that @ojdo solved that a little different than me.
- urbs: `usable_cap = cap_init + cap_new`, with `cap_new >=0`
- urbs.jl: `usable_cap = cap_avail` with `cap_min<=cap_avail<=cap_max`, just using `cap_init` when computing the cost.

That means that in my scenario, it is possible to gain money by downgrading `cap_avail` to smaller values than `cap_init`. It seems to me, the obvious solution would be to internally do:

``` julia
if cap_init > cap_min
  cap_min = cap_init
end
```

**Comment by ojdo** [comment]
The internal fix sounds reasonable, as it does not seem to change behaviour compared to urbs.py.
